### ISSUE TITLE
how to deal with

### ISSUE THREAD

**Issue by zzhcharmmer** [larshson/vboxwebber#1]
zzhcharmer@zzhcharmer:~$ python
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from vboxwebber import *
>>> mgr = IWebsessionManager2("http://localhost:18083")
>>> vbox = mgr.logon("zzhcharmer", "429919")
>>> print(vbox.getAPIVersion())
5_2
>>> machine = vbox.findMachine("mint")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zzhcharmer/.local/lib/python2.7/site-packages/vboxwebber/__init__.py", line 2424, in findMachine
    val = self.mgr.getService().IVirtualBox_findMachine(*req)
  File "/home/zzhcharmer/.local/lib/python2.7/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "/home/zzhcharmer/.local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/zzhcharmer/.local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 195, in process_reply
    return self.process_error(doc, operation)
  File "/home/zzhcharmer/.local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
    detail=fault_node.find("detail"),
zeep.exceptions.Fault: VirtualBox error: rc=0x80bb0001 Could not find a registered machine named 'mint' (0x80bb0001)

**Comment by larshson** [comment]
The answer from VirtualBox is stated by zeep in the end of the exception:

> Fault: VirtualBox error: rc=0x80bb0001 Could not find a registered machine named 'mint' (0x80bb0001)

This would indicate that you don't have a registered machine with the exact spelling 'mint' in VirtualBox?

Have you generated your own wrappers for version 5.2 or are you running the version from pip?

**Comment by zzhcharmmer** [comment]
how to generate my own wrappers for version 5.2



At 2020-03-15 13:53:29, "larshson" <notifications@github.com> wrote:

The answer from VirtualBox is stated by zeep in the end of the exception:

Fault: VirtualBox error: rc=0x80bb0001 Could not find a registered machine named 'mint' (0x80bb0001)

This would indicate that you don't have a registered machine with the exact spelling 'mint' in VirtualBox?

Have you generated your own wrappers for version 5.2 or are you running the version from pip?

**Comment by larshson** [comment]
> how to generate my own wrappers for version 5.2

It is stated in the readme:

> Just download the VirtualBox source code package, put the xsl stylesheet in src/VBox/Main/webservice and run:
> 
> xsltproc websrv-zeep.xsl ../idl/VirtualBox.xidl > vboxwebber.py
